//this file wrapps up all the files in the project
import "./globals.css"
import { Montserrat } from "@next/font/google"
import Nav from "./components/Nav"
import QueryWrapper from "@/pages/api/auth/QueryWrapper"

const montserrat = Montserrat({ //specific font from @next/font library
  weight:["400","900"],
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <QueryWrapper>
          <Nav/>
          <div className="p-10">
            {children}
          </div>
        </QueryWrapper>
      </body>
    </html>
  )
}
