//this file wrapps up all the files in the project
import "@/globals.css"
import Nav from "../src/components/server/Nav"
import QueryWrapper from "@/components/client/QueryWrapper"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QueryWrapper>
          <Nav />
          <div className="p-10 bg-gray-200">{children}</div>
        </QueryWrapper>
      </body>
    </html>
  )
}
