//this file wrapps up all the files in the project
import "./globals.css"
import { Montserrat } from "@next/font/google"
import NavBar from "./components/NavBar"

const montserrat = Montserrat({ //specific font from @next/font library
  weight:["400","900"],
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <NavBar />
        <div className="p-10">
          {children}
        </div>
      </body>
    </html>
  )
}
